//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ControlMgr.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_CONTROLMGR_DIALOG           102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_STATUS_MONITOR       129
#define IDD_DIALOG_TASK_MANAGER         130
#define IDD_DIALOG_TASK_LOG             132
#define IDC_BUTTON_MONITOR_STATUS       1002
#define IDC_BUTTON_TASK_MANAGER         1003
#define IDC_BUTTON_OPERATE_LOG          1004
#define IDC_STATIC_WINDOW               1005
#define IDC_STATIC_UDPPROXY_IP          1006
#define IDC_STATIC_UDPPROXY_PORT        1007
#define IDC_STATIC_UDPPROXY_STATUS      1008
#define IDC_STATIC_SENDSVR_IP           1009
#define IDC_STATIC_SENDSVR_PORT         1010
#define IDC_STATIC_SENDSVR_STATUS       1011
#define IDC_STATIC_RECVSVR_IP           1012
#define IDC_STATIC_RECVSVR_PORT         1013
#define IDC_STATIC_RECVSVR_STATUS       1014
#define IDC_LIST_SENDSVR_CLIENT         1015
#define IDC_BUTTON_UDPPROXY_START       1016
#define IDC_BUTTON_UDPPROXY_STOP        1017
#define IDC_EDIT_TASK_MANAGER_TASK_ID   1017
#define IDC_BUTTON_SENDSVR_START        1018
#define IDC_BUTTON_TASK_MANAGER_SEARCH  1018
#define IDC_BUTTON_SENDSVR_STOP         1019
#define IDC_LIST_TASK_MANAGER           1019
#define IDC_BUTTON_RECVSVR_START        1020
#define IDC_BUTTON_TASK_MGR_EDIT        1020
#define IDC_BUTTON_RECVSVR_STOP         1021
#define IDC_BUTTON_TASK_MGR_PLAY        1021
#define IDC_BUTTON_TASK_MGR_REFRESH     1022
#define IDC_DATETIMEPICKER_TASK_MGR_START 1023
#define IDC_BUTTON_TASK_MGR_PLAY2       1024
#define IDC_BUTTON_TASK_MGR_STOP        1024
#define IDC_DATETIMEPICKER_TASK_MGR_STOP 1025
#define IDC_EDIT_TASK_MGR_TIME_OUT      1027
#define IDC_BUTTON_TASK_LOG_REFRESH     1036
#define IDC_LIST_LOG_MANAGER            1037
#define IDC_LIST_TASK_LOG               1037
#define IDC_DATETIMEPICKER_TASK_LOG_START 1038
#define IDC_DATETIMEPICKER_TASK_LOG_STOP 1039
#define IDC_BUTTON_TASK_LOG_SEARCH      1040
#define IDC_BUTTON_TASK_LOG_EXPORT      1041
#define IDC_BUTTON_TASK_MGR_EXPORT      1042
#define IDC_STATIC_TASK_LOG_STARTTIME   1043
#define IDC_STATIC_TASK_LOG_STOP_TIME   1044
#define IDC_STATIC_TASK_MGR_START_TIME  1045
#define IDC_STATIC_TASK_MGR_STOP_TIME   1046
#define IDC_STATIC_TASK_MGR_ID          1047
#define IDC_STATIC_TASK_MONITOR_PROXY_IP 1048
#define IDC_STATIC_TASK_MONITOR_PROXY_PORT 1049
#define IDC_STATIC_TASK_MONITOR_PROXY_STATUS 1050
#define IDC_STATIC_TASK_MONITOR_SENDSVR_IP 1051
#define IDC_STATIC_TASK_MONITOR_SENDSVR_PORT 1052
#define IDC_STATIC_TASK_MONITOR_SENDSVR_STATUS 1053
#define IDC_STATIC_TASK_MONITOR_RECVSVR_IP 1054
#define IDC_STATIC_TASK_MONITOR_RECVSVR_PORT 1055
#define IDC_STATIC_TASK_MONITOR_RECVSVR_STATUS 1056

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        136
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1057
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
