//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by BarOnline.rc
//
#define IDCANCEL2                       3
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MainFrame                   102
#define IDR_MAINFRAME                   103
#define IDD_DLG_GONGGAO                 135
#define IDD_DLG_UPTPRG                  136
#define IDD_DLG_SYSSET                  137
#define IDD_DLG_UPTOPT                  138
#define IDD_DLG_HOTGAME                 139
#define IDD_DLG_FAVORITE                140
#define IDD_DLG_RBPOPADV                141
#define IDD_DLG_OPTLLOGIN               142
#define IDI_ONLINE_PROT                 143
#define IDI_ONLINE_NOPROT               148
#define IDI_NOONLINE_PROT               149
#define IDI_NOONLINE_NOPROT             150
#define IDR_TRAY_MENU                   152
#define IDD_DLG_MESSAGE                 153
#define IDD_DLG_DOCK                    154
#define IDD_DLG_CHECKDISK               155
#define IDD_DLG_GONGGAO_TRANS           157
#define IDD_DLG_GONGGAO_TRANS1          158
#define IDD_DLG_UPTPRG_TRANS            158
#define IDR_HTTPERROR                   160
#define IDR_ACCELERATOR1                161
#define IDR_JPG_404BTM                  162
#define IDR_JPG_404MID                  163
#define IDR_JPG_404PIC                  164
#define IDR_JPG4                        165
#define IDR_JPG_404TOP                  165
#define IDC_CLOSE                       1013
#define IDC_WELCOME                     1014
#define IDC_RUN                         1015
#define IDC_NBINFO                      1015
#define IDC_CONTEXT                     1016
#define IDC_SEARCH                      1017
#define IDC_QUICKLOGIN                  1018
#define IDC_BUYCARD                     1019
#define IDC_PERSON                      1020
#define IDC_GAMESAVE                    1021
#define IDC_VIDEOSKILL                  1021
#define IDC_REG                         1022
#define IDC_MODIFY                      1023
#define IDC_FINDPWD                     1024
#define IDC_FAVORITE                    1025
#define IDC_LOGIN                       1026
#define IDC_PROGRESS                    1027
#define IDC_STATUS                      1028
#define IDC_TIME                        1029
#define IDC_DEL                         1030
#define IDC_BTN_SEP                     1031
#define IDC_CAPTION                     1032
#define IDC_GAMEPLUG                    1033
#define IDC_SVR_IP                      1034
#define IDC_AREA_SET                    1035
#define IDC_AREA_UNPROT                 1036
#define IDC_AREA_PROT                   1037
#define IDC_EDIT_SVR_IP                 1038
#define IDC_ADD                         1039
#define IDC_ADDALL                      1040
#define IDC_DELALL                      1041
#define IDC_LEFT                        1042
#define IDC_RIGHT                       1043
#define IDC_PANEL                       1044
#define IDC_COMBO1                      1045
#define IDC_TOP_LINE                    1046
#define IDC_TITLE1                      1047
#define IDC_COMMENT1                    1048
#define IDC_GAME1                       1049
#define IDC_GAME2                       1050
#define IDC_NUMBER                      1051
#define IDC_LIST_GAME                   1052
#define IDC_BTN_LINE                    1053
#define IDC_BTN_FAV                     1054
#define IDC_BTN_CLOSE                   1055
#define IDC_TREE1                       1056
#define IDC_FAV_GAME                    1057
#define IDC_BTN_MANAGE                  1057
#define IDC_FAV_URL                     1058
#define IDC_FAV_URLMGR                  1059
#define IDC_RD_QUICK                    1060
#define IDC_RD_FORCE                    1061
#define IDC_TIP                         1063
#define IDC_PASSWORD                    1064
#define IDC_CONTENT                     1067
#define IDC_BUTTON1                     1069
#define IDC_BTN_TITLE                   1069
#define IDC_PLUG                        1070
#define IDC_BTN_DRVLIST                 1070
#define IDC_BTN_CHECKDRVLIST            1071
#define IDC_BTN_CHECKDISK               1072
#define IDC_BTN_ADD                     1072
#define IDC_LST_LEFT                    1073
#define IDC_LST_RIGHT                   1074
#define IDC_BTN_ADDALL                  1075
#define IDC_BTN_DEL                     1076
#define IDC_BTN_DELALL                  1077
#define IDC_BTN_CHECK                   1078
#define IDC_BTN_CANCEL                  1079
#define ID_TRAYMENU_32771               32771
#define ID_TRAYMENU_32772               32772
#define ID_TRAYMENU_32773               32773
#define ID_TRAYMENU_32774               32774
#define ID_TRAYMENU_32775               32775
#define ID_TRAYMENU_32776               32776
#define ID_TRAYMENU_32777               32777
#define ID_TRAY_EXIT                    32778
#define ID_TRAY_BROWSE                  32779
#define ID_TRAY_GAMEROOM                32780
#define ID_TRAY_DOTCARD                 32781
#define ID_TRAY_VDMUSIC                 32782
#define ID_TRAY_WLGAME                  32783
#define ID_TRAY_DJGAME                  32785
#define ID_Menu                         32786
#define ID_TRAYMENU_32787               32787
#define ID_TRAY_CHAT                    32788
#define ID_TRAY_SOFTWARE                32789
#define ID_LISTMENU_32790               32790
#define ID_LISTMENU_32791               32791
#define ID_LISTMENU_32792               32792
#define ID_POP_RUNGAME                  32793
#define ID_POP_OPENDIR                  32794
#define ID_POP_SEARCHGAME               32795
#define ID_Menu32796                    32796
#define ID_LISTMENU_32797               32797
#define ID_POP_ADD_GAME_FAV             32798
#define ID_POP_HOLD                     32799
#define ID_LISTMENU_32800               32800
#define ID_POP_SAVE_PROGRESS            32801
#define ID_LISTMENU_32802               32802
#define ID_POP_LOAD_PROGRESS            32803

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        166
#define _APS_NEXT_COMMAND_VALUE         32805
#define _APS_NEXT_CONTROL_VALUE         1074
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
